# playbook-launch-ec2.yml
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        wait: true
        count: 1
        tags:
          Name: webserver
        vpc_subnet_id: 'subnet-05013b3bb416ce20d'     # Replace with valid subnet
        security_group: "{{ security_group }}"
      register: ec2_result

    
    # Optional: Debug output to inspect structure
    - name: Show full EC2 instance details (for debug)
      debug:
        var: ec2_result.instances[0]

    - name: Save instance public IP to inventory file
      copy:
        content: |
          [web]
          {{ ec2_result.instances[0].network_interfaces[0].association.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=./demo.pem
        dest: ./inventory.ini

    - name: Set permissions on inventory file
      file:
        path: ./inventory.ini
        mode: '0600'
